# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
before_install:
  - sudo apt-get install libstdc++6
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade
language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
