# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
before_install:
  - sudo apt-get install libstdc++6
language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
